server:
  port: 8080

spring:
  cloud:
    gateway:
      routes:
        - id: menu
          uri: http://localhost:8081/
          predicates:
            - Path=/menu/**
        - id: order
          uri: http://localhost:8082/
          predicates:
            - Path=/order/**
        - id: stock
          uri: http://localhost:8083/
          predicates:
            - Path=/stock/**